#!/usr/bin/env python
"""Initialize memory-governance files in a target project."""
from __future__ import annotations

import argparse
from pathlib import Path

from scripts.resources import resource_path


def read_template(name: str) -> str:
    return resource_path(f"templates/{name}").read_text(encoding="utf-8")


def render(text: str, project_name: str, notes_namespace: str, context_file: str) -> str:
    return (
        text.replace("<project-name>", project_name)
        .replace("<project-notes-namespace>", notes_namespace)
        .replace("<project-context-file>", context_file)
        .replace("<project-notes-index>", f"{notes_namespace.rstrip('/')}/00_Index.md")
    )


def write_if_missing(path: Path, content: str, force: bool) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        return f"skip existing {path}"
    path.write_text(content, encoding="utf-8", newline="\n")
    return f"write {path}"


def build_handoff_index(context_file: str, notes_namespace: str) -> str:
    return f"""# Handoff Index

Status: active

## Read first

1. `{context_file}`
2. `handoff/memory_governance.md`
3. `handoff/active_strategy_queue.md`
4. `handoff/accepted_changes.md`
5. `{notes_namespace.rstrip('/')}/00_Index.md`

## Rolling worker IPC

- `handoff/worker_tasks/`
- `handoff/reviews/`

## Moved out of handoff root

- Long-term rationale: `{notes_namespace}`
- Logs/receipts: `logs/` if needed
- Archives: `handoff/archive/` if needed
"""


def build_notes_index(project_name: str) -> str:
    return f"""# {project_name} Notes Index

Status: active
Source: generated by multi-project-memory-governance
Date: YYYY-MM-DD
Repo truth: handoff/memory_governance.md

## Active notes

- Memory governance: `handoff/memory_governance.md`
- Current queue: `handoff/active_strategy_queue.md`

## Rule

Long-term rationale belongs in this notes namespace. Engineering truth belongs in repo handoff.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=".", help="Target project directory")
    parser.add_argument("--project-name", required=True, help="Human-readable project name")
    parser.add_argument("--notes-namespace", required=True, help="Project notes path relative to target")
    parser.add_argument("--context-file", default=".hermes.md", help="Primary project context file")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args(argv)

    target = Path(args.target).resolve()
    notes_namespace = args.notes_namespace.strip("/")
    actions = []
    actions.append(write_if_missing(target / "handoff" / "memory_governance.md", render(read_template("handoff-memory-governance.md"), args.project_name, notes_namespace, args.context_file), args.force))
    actions.append(write_if_missing(target / "handoff" / "active_strategy_queue.md", render(read_template("active-strategy-queue.md"), args.project_name, notes_namespace, args.context_file), args.force))
    actions.append(write_if_missing(target / "handoff" / "INDEX.md", build_handoff_index(args.context_file, notes_namespace), args.force))
    actions.append(write_if_missing(target / "handoff" / "accepted_changes.md", "# Accepted Changes\n\n", args.force))
    actions.append(write_if_missing(target / "handoff" / "worker_tasks" / "README.md", "# Worker Tasks\n\nUse bounded worker task files here.\n", args.force))
    actions.append(write_if_missing(target / "handoff" / "reviews" / "README.md", "# Reviews\n\nUse review-output artifacts here.\n", args.force))
    actions.append(write_if_missing(target / notes_namespace / "00_Index.md", build_notes_index(args.project_name), args.force))
    context_path = target / args.context_file
    if not context_path.exists() or args.force:
        context = f"# {args.project_name} agent context\n\n" + render(
            read_template("project-context-snippet.md"),
            args.project_name,
            notes_namespace,
            args.context_file,
        )
        actions.append(write_if_missing(context_path, context, args.force))
    else:
        actions.append(f"skip existing {context_path}; merge templates/project-context-snippet.md manually if needed")
    print("\n".join(actions))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
